spring.application.name=auth-service

server.port=4005
server.address=0.0.0.0

logging.level.root=info

jwt.secret=mysupersecurejwtsecretkey1234567890abcd

# ? Actuator configs
management.endpoints.web.exposure.include=mappings,health,info
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator